### ISSUE TITLE
Unable to load Blockstack browser after upgrade to v0.20.0

### ISSUE THREAD

**Issue by sinzin91** [blockstack/blockstack-browser#1020]
I get this error in the console when opening Blockstack browser `v0.20.0`:

```
main.js:14479 
Uncaught TypeError: state.localIdentities.slice is not a function
    at IdentityReducer (main.js:14479)
    at combination (main.js:192691)
    at combination (main.js:192691)
    at RootReducer (main.js:15841)
    at computeNextEntry (main.js:189983)
    at recomputeStates (main.js:190017)
    at main.js:190401
    at dispatch (main.js:192917)
    at createStore (main.js:192992)
    at main.js:192353
popup.js:3 
Uncaught ReferenceError: $ is not defined
    at popup.js:3
```
The app does not load.

`v0.16.0` worked just fine

**Comment by garrettqmartin8** [comment]
Same issue here!

**Comment by sean9999** [comment]
what's the most functional release? 0.16.0?

**Comment by sinzin91** [comment]
@sean9999 v0.19.1 seems to load fine, but I have a separate issue with that release

**Comment by ktal90** [comment]
Seeing the same on 0.21.5:

```
main.js:15216 Uncaught TypeError: state.localIdentities.slice is not a function
    at IdentityReducer (main.js:15216)
    at combination (main.js:193636)
    at combination (main.js:193636)
    at RootReducer (main.js:16578)
    at computeNextEntry (main.js:190928)
    at recomputeStates (main.js:190962)
    at main.js:191346
    at dispatch (main.js:193862)
    at createStore (main.js:193937)
    at main.js:193298
```

**Comment by ktal90** [comment]
I cleared my localhost and blockstack-related cookies, and this issue cleared up.

**Comment by wbobeirne** [comment]
Closing as stale, sorry for the inconveniences y'all. Please re-open if you're still running into this.
